add wave -position insertpoint \
    -radix binary \
	/tb_quad/QuadA0DataOut \
	/tb_quad/QA0CountRead \
	/tb_quad/QA0LEDStatusRead \
	/tb_quad/QA0LEDStatusWrite \
	/tb_quad/QA0InputRead \
	/tb_quad/QA0HomeRead \
	/tb_quad/QA0Latch0Read \
	/tb_quad/QA0Latch1Read \
	/tb_quad/QA0_Home \
	/tb_quad/QA0_RegX_PosLmt \
	/tb_quad/QA0_RegY_NegLmt \
	/tb_quad/QA0_SigA \
	/tb_quad/QA0_SigB \
	/tb_quad/QuadA1DataOut \
	/tb_quad/QA1CountRead \
	/tb_quad/QA1LEDStatusRead \
	/tb_quad/QA1LEDStatusWrite \
	/tb_quad/QA1InputRead \
	/tb_quad/QA1HomeRead \
	/tb_quad/QA1Latch0Read \
	/tb_quad/QA1Latch1Read \
	/tb_quad/QA1_Home \
	/tb_quad/QA1_RegX_PosLmt \
	/tb_quad/QA1_RegY_NegLmt \
	/tb_quad/QA1_SigA \
	/tb_quad/QA1_SigB \
	/tb_quad/Exp0Quad_A \
	/tb_quad/Exp0Quad_B \
	/tb_quad/Exp0Quad_FaultA \
	/tb_quad/Exp0Quad_FaultB \
	/tb_quad/Exp0Quad_Reg \
	/tb_quad/Exp0QuadCountRead \
	/tb_quad/Exp0QuadDataOut \
	/tb_quad/Exp0QuadHomeRead \
	/tb_quad/Exp0QuadInputRead \
	/tb_quad/Exp0QuadLatch0Read \
	/tb_quad/Exp0QuadLatch1Read \
	/tb_quad/Exp0QuadLEDStatusRead \
	/tb_quad/Exp0QuadLEDStatusWrite \
	/tb_quad/Exp1Quad_A \
	/tb_quad/Exp1Quad_B \
	/tb_quad/Exp1Quad_FaultA \
	/tb_quad/Exp1Quad_FaultB \
	/tb_quad/Exp1Quad_Reg \
	/tb_quad/Exp1QuadCountRead \
	/tb_quad/Exp1QuadDataOut \
	/tb_quad/Exp1QuadHomeRead \
	/tb_quad/Exp1QuadInputRead \
	/tb_quad/Exp1QuadLatch0Read \
	/tb_quad/Exp1QuadLatch1Read \
	/tb_quad/Exp1QuadLEDStatusRead \
	/tb_quad/Exp1QuadLEDStatusWrite \
	/tb_quad/Exp2Quad_A \
	/tb_quad/Exp2Quad_B \
	/tb_quad/Exp2Quad_FaultA \
	/tb_quad/Exp2Quad_FaultB \
	/tb_quad/Exp2Quad_Reg \
	/tb_quad/Exp2QuadCountRead \
	/tb_quad/Exp2QuadDataOut \
	/tb_quad/Exp2QuadHomeRead \
	/tb_quad/Exp2QuadInputRead \
	/tb_quad/Exp2QuadLatch0Read \
	/tb_quad/Exp2QuadLatch1Read \
	/tb_quad/Exp2QuadLEDStatusRead \
	/tb_quad/Exp2QuadLEDStatusWrite \
	/tb_quad/Exp3Quad_A \
	/tb_quad/Exp3Quad_B \
	/tb_quad/Exp3Quad_FaultA \
	/tb_quad/Exp3Quad_FaultB \
	/tb_quad/Exp3Quad_Reg \
	/tb_quad/Exp3QuadCountRead \
	/tb_quad/Exp3QuadDataOut \
	/tb_quad/Exp3QuadHomeRead \
	/tb_quad/Exp3QuadInputRead \
	/tb_quad/Exp3QuadLatch0Read \
	/tb_quad/Exp3QuadLatch1Read \
	/tb_quad/Exp3QuadLEDStatusRead \
	/tb_quad/Exp3QuadLEDStatusWrite
